### ISSUE TITLE
Building Transaction/TxnManagerOcc.cpp.o fails

### ISSUE THREAD

**Issue by nisargshah95** [Cavalia/Cavalia#6]
OS: Ubuntu 18.04
g++ version: 4.8

Error snippet -
```
[ 30%] Building CXX object Database/CMakeFiles/database_static.dir/Transaction/TxnManagerOcc.cpp.o
cd /fastdisk/Cavalia/build/Database && /usr/bin/g++-4.8   -I/fastdisk/Cavalia/Common -I/fastdisk/Cavalia/Database  -std=c++11 -Wno-deprecated-declarations -DOCC -O0 -g   -o CMakeFiles/database_static.dir/Transaction/TxnManagerOcc.cpp.o -c /fastdisk/Cavalia/Database/Transaction/TxnManagerOcc.cpp
In file included from /fastdisk/Cavalia/Common/RWLock.h:6:0,
                 from /fastdisk/Cavalia/Database/Transaction/../Logger/../Transaction/../Storage/../Content/LockContent.h:6,
                 from /fastdisk/Cavalia/Database/Transaction/../Logger/../Transaction/../Storage/TableRecord.h:10,
                 from /fastdisk/Cavalia/Database/Transaction/../Logger/../Transaction/TxnAccess.h:9,
                 from /fastdisk/Cavalia/Database/Transaction/../Logger/BaseLogger.h:17,
                 from /fastdisk/Cavalia/Database/Transaction/../Logger/ValueLogger.h:5,
                 from /fastdisk/Cavalia/Database/Transaction/TransactionManager.h:9,
                 from /fastdisk/Cavalia/Database/Transaction/TxnManagerOcc.cpp:2:
/fastdisk/Cavalia/Common/SpinLock.h: In member function ‘bool SpinLock::IsLocked() const’:
/fastdisk/Cavalia/Common/SpinLock.h:67:23: error: no match for ‘operator==’ (operand types are ‘const std::atomic_flag’ and ‘int’)
   return spinlock_.v_ == 1;
                       ^
```
Complete error trace -
[cavalia make.log](https://github.com/Cavalia/Cavalia/files/3917873/cavalia.make.log)

**Comment by yingjunwu** [comment]
@nisargshah95 possibly to be a boost library issue (boost evolves too fast). You may add macro `PTHREAD_LOCK` in CMakeLists.txt (https://github.com/Cavalia/Cavalia/blob/master/CMakeLists.txt, e.g., add `-DPTHREAD_LOCK` right after `-DOCC`)  to use pthread lock or add `BUILTIN_LOCK` to use builtin lock. Or you can directly define the macro at the begining of the `SpinLock.h` file.

You may also check boost documentation (depending on your boost version) to see how to check whether lock is on.

I personally do not use boost often due to this kind of issues.

**Comment by yingjunwu** [comment]
or you may try this: change the line `return spinlock_.v_== 1;` to `return spinlock_.v_ != ATOMIC_FLAG_INIT;`. Not sure whether it works but seems that it would be the right solution as boost internally uses `std::atomic_flag` in this case.

**Comment by nisargshah95** [comment]
Thanks! I added `PTHREAD_LOCK` macro to CMakeLists.txt file and it built successfully.
